name: Release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write   # allow uploading assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: python -m pip install --upgrade pip build
      - run: python -m build .
      - name: List artifacts (debug)
        run: ls -al dist || dir dist
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
